config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmark_path(@bookmark)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>




<p><%= link_to "add a movie", new_bookmark_path %></p>
<p><%= link_to "back to list", lists_path %></p>

app/views/bookmarks/new.html.erb
<div class="container text-center">
  <h1>Add a bookmark to <%= @bookmark.comment %></h1>
  <div class="d-flex justify-content-center align-items-center">
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie %>
      <%= f.input :comment %>
      <%= f.submit %>
    <% end %>
  </div>

  <p><%= link_to "back", lists_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
    <div class="navbar">
      <img class="avatar-large "src="https://res.cloudinary.com/dipnvqfev/image/upload/v1668872424/development/gr-stocks-q8P8YoR6erg-unsplash_wzsofc.jpg" alt="">
      <p><%= link_to "add a new list", new_list_path %></p>
    </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dipnvqfev/image/upload/v1668865637/development/geoffrey-moffett-TFRezw7pQwI-unsplash_cbu6b1.jpg);">
  <div class="container">
    <h1>Select <strong>your</strong> favorite <strong>movies</strong>!</h1>
  </div>
</div>

<div class="container text-center">
  <h2>My lists</h2>
    <div class="row">
      <% @lists.each do|list| %>
        <div class="col-3">
          <div class="card-trip">
            <p><%= link_to list.name, list_path(list) %></p>
            <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
            <p><%= link_to "🗑️", list_path(list),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name%>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

<p><%= link_to "back", lists_path %></p>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li><p><%= bookmark.movie.title %></p></li>
    <p><%= link_to "delete", bookmark_path(bookmark),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
  <% end %>
</ul>

<%= link_to "add a movie", new_list_bookmark_path(@list)%>

<%= link_to "back", lists_path %>